swagger: "2.0"
info:
  description: "bankapp2"
  version: "2.0.0"
  title: "bankapp2"
host: "localhost:8080"
basePath: "/v2
schemes:
  - "http"
paths:
  /users:
    get:
      summary: "Get list of users"
      responses:
        200:
          description: "Ok"
          schema:
            type: array
            items:
              $ref: "#/definitions/User"
        default:
          description: Общая ошибка
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      summary: "Create a new user"
      parameters:
        - in: body
          name: user
          description: "User to be created"
          required: true
          schema:
            $ref: "#/definitions/NewUser"
      responses:
        201:
          description: "User created"
          schema:
            $ref: "#/definitions/User"
        default:
          description: Общая ошибка
          schema:
            $ref: "#/definitions/ErrorResponse"
    patch:
      summary: "Patch user"
      parameters:
        - in: body
          name: user
          description: "User patched"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        201:
          description: "User patched"
          schema:
            $ref: "#/definitions/User"
        default:
          description: Общая ошибка
          schema:
            $ref: "#/definitions/ErrorResponse"
  /users/{id}:
    get:
      summary: "Get a user by ID"
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: "Ok"
          schema:
            $ref: "#/definitions/User"
        404:
          description: "User not found"
        default:
          description: Общая ошибка
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      summary: "Delete a user by ID"
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        204:
          description: "User deleted"
        default:
          description: Общая ошибка
          schema:
            $ref: "#/definitions/ErrorResponse"
  /cards:
    get:
      summary: "Get list of cards"
      responses:
        200:
          description: "Ok"
          schema:
            type: array
            items:
              $ref: "#/definitions/Card"
        default:
          description: Общая ошибка
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      summary: "Create a new card"
      parameters:
        - in: body
          name: card
          description: "Card to be created"
          required: true
          schema:
            $ref: "#/definitions/NewCard"
      responses:
        201:
          description: "Card created"
          schema:
            $ref: "#/definitions/Card"
        default:
          description: Общая ошибка
          schema:
            $ref: "#/definitions/ErrorResponse"
    patch:
      summary: "Patch card"
      parameters:
        - in: body
          name: card
          description: "Card to be patched"
          required: true
          schema:
            $ref: "#/definitions/Card"
      responses:
        201:
          description: "Card patched"
          schema:
            $ref: "#/definitions/Card"
        default:
          description: Общая ошибка
          schema:
            $ref: "#/definitions/ErrorResponse"
  /cards/{id}:
    get:
      summary: "Get a card by ID"
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: "Ok"
          schema:
            $ref: "#/definitions/Card"
        404:
          description: "Card not found"
        default:
          description: Общая ошибка
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      summary: "Delete a card by ID"
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        204:
          description: "Card deleted"
        default:
          description: Общая ошибка
          schema:
            $ref: "#/definitions/ErrorResponse"
  /banks:
    get:
      summary: "Get list of banks"
      responses:
        200:
          description: "Ok"
          schema:
            type: array
            items:
              $ref: "#/definitions/Bank"
        default:
          description: Общая ошибка
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      summary: "Create a new bank"
      parameters:
        - in: body
          name: bank
          description: "Bank to be created"
          required: true
          schema:
            $ref: "#/definitions/NewBank"
      responses:
        201:
          description: "Bank created"
          schema:
            $ref: "#/definitions/Bank"
        default:
          description: Общая ошибка
          schema:
            $ref: "#/definitions/ErrorResponse"
    patch:
      summary: "Patch bank"
      parameters:
        - in: body
          name: bank
          description: "Bank patched"
          required: true
          schema:
            $ref: "#/definitions/Bank"
      responses:
        201:
          description: "Bank patched"
          schema:
            $ref: "#/definitions/Bank"
        default:
          description: Общая ошибка
          schema:
            $ref: "#/definitions/ErrorResponse"
  /banks/{id}:
    get:
      summary: "Get a bank by ID"
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: "Ok"
          schema:
            $ref: "#/definitions/Bank"
        404:
          description: "Bank not found"
        default:
          description: Общая ошибка
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      summary: "Delete a bank by ID"
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        204:
          description: "Bank deleted"
        default:
          description: Общая ошибка
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
  NewUser:
    type: object
    properties:
      email:
        type: string
        x-go-custom-tag: "validate:\"required\""
      firstName:
        type: string
        x-go-custom-tag: "validate:\"required\""
      lastName:
        type: string
        x-go-custom-tag: "validate:\"required\""
  Bank:
    type: object
    properties:
      id:
        type: integer
      Name:
        type: string
  NewBank:
    type: object
    properties:
      Name:
        type: string
        x-go-custom-tag: "validate:\"required\""
  Card:
    type: object
    properties:
      id:
        type: integer
      UserID:
        type: integer
      BankID:
        type: integer
      Number:
        type: integer
      CreateDate:
        type: string
        format: date-time
      ExpiryDate:
        type: string
        format: date
      Total:
        type: integer
  NewCard:
    type: object
    properties:
      UserID:
        type: integer
        x-go-custom-tag: "validate:\"required\""
      BankID:
        type: integer
        x-go-custom-tag: "validate:\"required\""
      Number:
        type: integer
        x-go-custom-tag: "validate:\"required\""
      CreateDate:
        type: string
        format: date-time
      ExpiryDate:
        type: string
        format: date
        x-go-custom-tag: "validate:\"required\""
      Total:
        type: integer
  ErrorResponse:
    title: ErrorResponse
    description: Общая ошибка
    allOf:
      - properties:
          error:
            type: object
            properties:
              message:
                description: Message
                type: string