CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(50) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS banks (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS cards (
    id BIGSERIAL PRIMARY KEY,
    userid BIGSERIAL NOT NULL,
    bankid BIGSERIAL NOT NULL,
    FOREIGN KEY (userid) REFERENCES users(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY (bankid) REFERENCES banks(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    card_number BIGINT NOT NULL,
    create_date TIMESTAMP WITHOUT TIME ZONE,
    expire_date TIMESTAMP WITHOUT TIME ZONE,
    total BIGINT NOT NULL
);