// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"bankapp2/app/models"
)

// DeleteBanksIDNoContentCode is the HTTP code returned for type DeleteBanksIDNoContent
const DeleteBanksIDNoContentCode int = 204

/*
DeleteBanksIDNoContent Bank deleted

swagger:response deleteBanksIdNoContent
*/
type DeleteBanksIDNoContent struct {
}

// NewDeleteBanksIDNoContent creates DeleteBanksIDNoContent with default headers values
func NewDeleteBanksIDNoContent() *DeleteBanksIDNoContent {

	return &DeleteBanksIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteBanksIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*
DeleteBanksIDDefault Общая ошибка

swagger:response deleteBanksIdDefault
*/
type DeleteBanksIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewDeleteBanksIDDefault creates DeleteBanksIDDefault with default headers values
func NewDeleteBanksIDDefault(code int) *DeleteBanksIDDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteBanksIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete banks ID default response
func (o *DeleteBanksIDDefault) WithStatusCode(code int) *DeleteBanksIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete banks ID default response
func (o *DeleteBanksIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete banks ID default response
func (o *DeleteBanksIDDefault) WithPayload(payload *models.ErrorResponse) *DeleteBanksIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete banks ID default response
func (o *DeleteBanksIDDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBanksIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
