// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteCardsIDHandlerFunc turns a function with the right signature into a delete cards ID handler
type DeleteCardsIDHandlerFunc func(DeleteCardsIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteCardsIDHandlerFunc) Handle(params DeleteCardsIDParams) middleware.Responder {
	return fn(params)
}

// DeleteCardsIDHandler interface for that can handle valid delete cards ID params
type DeleteCardsIDHandler interface {
	Handle(DeleteCardsIDParams) middleware.Responder
}

// NewDeleteCardsID creates a new http.Handler for the delete cards ID operation
func NewDeleteCardsID(ctx *middleware.Context, handler DeleteCardsIDHandler) *DeleteCardsID {
	return &DeleteCardsID{Context: ctx, Handler: handler}
}

/*
	DeleteCardsID swagger:route DELETE /cards/{id} deleteCardsId

Delete a card by ID
*/
type DeleteCardsID struct {
	Context *middleware.Context
	Handler DeleteCardsIDHandler
}

func (o *DeleteCardsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteCardsIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
