// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteBanksIDHandlerFunc turns a function with the right signature into a delete banks ID handler
type DeleteBanksIDHandlerFunc func(DeleteBanksIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteBanksIDHandlerFunc) Handle(params DeleteBanksIDParams) middleware.Responder {
	return fn(params)
}

// DeleteBanksIDHandler interface for that can handle valid delete banks ID params
type DeleteBanksIDHandler interface {
	Handle(DeleteBanksIDParams) middleware.Responder
}

// NewDeleteBanksID creates a new http.Handler for the delete banks ID operation
func NewDeleteBanksID(ctx *middleware.Context, handler DeleteBanksIDHandler) *DeleteBanksID {
	return &DeleteBanksID{Context: ctx, Handler: handler}
}

/*
	DeleteBanksID swagger:route DELETE /banks/{id} deleteBanksId

Delete a bank by ID
*/
type DeleteBanksID struct {
	Context *middleware.Context
	Handler DeleteBanksIDHandler
}

func (o *DeleteBanksID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteBanksIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
