// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"bankapp2/app/models"
)

// GetBanksIDOKCode is the HTTP code returned for type GetBanksIDOK
const GetBanksIDOKCode int = 200

/*
GetBanksIDOK Ok

swagger:response getBanksIdOK
*/
type GetBanksIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Bank `json:"body,omitempty"`
}

// NewGetBanksIDOK creates GetBanksIDOK with default headers values
func NewGetBanksIDOK() *GetBanksIDOK {

	return &GetBanksIDOK{}
}

// WithPayload adds the payload to the get banks Id o k response
func (o *GetBanksIDOK) WithPayload(payload *models.Bank) *GetBanksIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get banks Id o k response
func (o *GetBanksIDOK) SetPayload(payload *models.Bank) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBanksIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBanksIDNotFoundCode is the HTTP code returned for type GetBanksIDNotFound
const GetBanksIDNotFoundCode int = 404

/*
GetBanksIDNotFound Bank not found

swagger:response getBanksIdNotFound
*/
type GetBanksIDNotFound struct {
}

// NewGetBanksIDNotFound creates GetBanksIDNotFound with default headers values
func NewGetBanksIDNotFound() *GetBanksIDNotFound {

	return &GetBanksIDNotFound{}
}

// WriteResponse to the client
func (o *GetBanksIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

/*
GetBanksIDDefault Общая ошибка

swagger:response getBanksIdDefault
*/
type GetBanksIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetBanksIDDefault creates GetBanksIDDefault with default headers values
func NewGetBanksIDDefault(code int) *GetBanksIDDefault {
	if code <= 0 {
		code = 500
	}

	return &GetBanksIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get banks ID default response
func (o *GetBanksIDDefault) WithStatusCode(code int) *GetBanksIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get banks ID default response
func (o *GetBanksIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get banks ID default response
func (o *GetBanksIDDefault) WithPayload(payload *models.ErrorResponse) *GetBanksIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get banks ID default response
func (o *GetBanksIDDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBanksIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
