// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetBanksHandlerFunc turns a function with the right signature into a get banks handler
type GetBanksHandlerFunc func(GetBanksParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBanksHandlerFunc) Handle(params GetBanksParams) middleware.Responder {
	return fn(params)
}

// GetBanksHandler interface for that can handle valid get banks params
type GetBanksHandler interface {
	Handle(GetBanksParams) middleware.Responder
}

// NewGetBanks creates a new http.Handler for the get banks operation
func NewGetBanks(ctx *middleware.Context, handler GetBanksHandler) *GetBanks {
	return &GetBanks{Context: ctx, Handler: handler}
}

/*
	GetBanks swagger:route GET /banks getBanks

Get list of banks
*/
type GetBanks struct {
	Context *middleware.Context
	Handler GetBanksHandler
}

func (o *GetBanks) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetBanksParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
