// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"bankapp2/app/models"
)

// NewPatchCardsParams creates a new PatchCardsParams object
//
// There are no default values defined in the spec.
func NewPatchCardsParams() PatchCardsParams {

	return PatchCardsParams{}
}

// PatchCardsParams contains all the bound params for the patch cards operation
// typically these are obtained from a http.Request
//
// swagger:parameters PatchCards
type PatchCardsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Card to be patched
	  Required: true
	  In: body
	*/
	Card *models.Card
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPatchCardsParams() beforehand.
func (o *PatchCardsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Card
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("card", "body", ""))
			} else {
				res = append(res, errors.NewParseError("card", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Card = &body
			}
		}
	} else {
		res = append(res, errors.Required("card", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
