// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"bankapp2/app/models"
)

// PatchUsersCreatedCode is the HTTP code returned for type PatchUsersCreated
const PatchUsersCreatedCode int = 201

/*
PatchUsersCreated User patched

swagger:response patchUsersCreated
*/
type PatchUsersCreated struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewPatchUsersCreated creates PatchUsersCreated with default headers values
func NewPatchUsersCreated() *PatchUsersCreated {

	return &PatchUsersCreated{}
}

// WithPayload adds the payload to the patch users created response
func (o *PatchUsersCreated) WithPayload(payload *models.User) *PatchUsersCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch users created response
func (o *PatchUsersCreated) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchUsersCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
PatchUsersDefault Общая ошибка

swagger:response patchUsersDefault
*/
type PatchUsersDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPatchUsersDefault creates PatchUsersDefault with default headers values
func NewPatchUsersDefault(code int) *PatchUsersDefault {
	if code <= 0 {
		code = 500
	}

	return &PatchUsersDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the patch users default response
func (o *PatchUsersDefault) WithStatusCode(code int) *PatchUsersDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the patch users default response
func (o *PatchUsersDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the patch users default response
func (o *PatchUsersDefault) WithPayload(payload *models.ErrorResponse) *PatchUsersDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch users default response
func (o *PatchUsersDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchUsersDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
