// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PatchUsersHandlerFunc turns a function with the right signature into a patch users handler
type PatchUsersHandlerFunc func(PatchUsersParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchUsersHandlerFunc) Handle(params PatchUsersParams) middleware.Responder {
	return fn(params)
}

// PatchUsersHandler interface for that can handle valid patch users params
type PatchUsersHandler interface {
	Handle(PatchUsersParams) middleware.Responder
}

// NewPatchUsers creates a new http.Handler for the patch users operation
func NewPatchUsers(ctx *middleware.Context, handler PatchUsersHandler) *PatchUsers {
	return &PatchUsers{Context: ctx, Handler: handler}
}

/*
	PatchUsers swagger:route PATCH /users patchUsers

Patch user
*/
type PatchUsers struct {
	Context *middleware.Context
	Handler PatchUsersHandler
}

func (o *PatchUsers) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPatchUsersParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
