// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PatchCardsHandlerFunc turns a function with the right signature into a patch cards handler
type PatchCardsHandlerFunc func(PatchCardsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchCardsHandlerFunc) Handle(params PatchCardsParams) middleware.Responder {
	return fn(params)
}

// PatchCardsHandler interface for that can handle valid patch cards params
type PatchCardsHandler interface {
	Handle(PatchCardsParams) middleware.Responder
}

// NewPatchCards creates a new http.Handler for the patch cards operation
func NewPatchCards(ctx *middleware.Context, handler PatchCardsHandler) *PatchCards {
	return &PatchCards{Context: ctx, Handler: handler}
}

/*
	PatchCards swagger:route PATCH /cards patchCards

Patch card
*/
type PatchCards struct {
	Context *middleware.Context
	Handler PatchCardsHandler
}

func (o *PatchCards) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPatchCardsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
