// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"bankapp2/app/models"
)

// NewPatchBanksParams creates a new PatchBanksParams object
//
// There are no default values defined in the spec.
func NewPatchBanksParams() PatchBanksParams {

	return PatchBanksParams{}
}

// PatchBanksParams contains all the bound params for the patch banks operation
// typically these are obtained from a http.Request
//
// swagger:parameters PatchBanks
type PatchBanksParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Bank patched
	  Required: true
	  In: body
	*/
	Bank *models.Bank
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPatchBanksParams() beforehand.
func (o *PatchBanksParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Bank
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("bank", "body", ""))
			} else {
				res = append(res, errors.NewParseError("bank", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Bank = &body
			}
		}
	} else {
		res = append(res, errors.Required("bank", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
