// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostCardsHandlerFunc turns a function with the right signature into a post cards handler
type PostCardsHandlerFunc func(PostCardsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostCardsHandlerFunc) Handle(params PostCardsParams) middleware.Responder {
	return fn(params)
}

// PostCardsHandler interface for that can handle valid post cards params
type PostCardsHandler interface {
	Handle(PostCardsParams) middleware.Responder
}

// NewPostCards creates a new http.Handler for the post cards operation
func NewPostCards(ctx *middleware.Context, handler PostCardsHandler) *PostCards {
	return &PostCards{Context: ctx, Handler: handler}
}

/*
	PostCards swagger:route POST /cards postCards

Create a new card
*/
type PostCards struct {
	Context *middleware.Context
	Handler PostCardsHandler
}

func (o *PostCards) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostCardsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
