// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostBanksHandlerFunc turns a function with the right signature into a post banks handler
type PostBanksHandlerFunc func(PostBanksParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostBanksHandlerFunc) Handle(params PostBanksParams) middleware.Responder {
	return fn(params)
}

// PostBanksHandler interface for that can handle valid post banks params
type PostBanksHandler interface {
	Handle(PostBanksParams) middleware.Responder
}

// NewPostBanks creates a new http.Handler for the post banks operation
func NewPostBanks(ctx *middleware.Context, handler PostBanksHandler) *PostBanks {
	return &PostBanks{Context: ctx, Handler: handler}
}

/*
	PostBanks swagger:route POST /banks postBanks

Create a new bank
*/
type PostBanks struct {
	Context *middleware.Context
	Handler PostBanksHandler
}

func (o *PostBanks) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostBanksParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
