// Code generated by go-swagger; DO NOT EDIT.

// Package restapi bankapp2
//
//	bankapp2
//	Schemes:
//	  http
//	Host: localhost:8080
//	BasePath: /v2
//	Version: 2.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
