ALTER TABLE users
    DROP CONSTRAINT users_pkey,
    ALTER COLUMN id TYPE BIGSERIAL;
ALTER TABLE users
    ADD PRIMARY KEY (id);

ALTER TABLE banks
    DROP CONSTRAINT banks_pkey,
    ALTER COLUMN id TYPE BIGSERIAL;
ALTER TABLE banks
    ADD PRIMARY KEY (id);

ALTER TABLE cards
    DROP CONSTRAINT cards_pkey,
    ALTER COLUMN id TYPE BIGSERIAL;
ALTER TABLE cards
    ADD PRIMARY KEY (id);